//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrazaNota
    {
        public int Id { get; set; }
        public int Alumnos_Materias_Id { get; set; }
        public int ValorAnterior { get; set; }
        public int ValorNuevo { get; set; }
        public int ProfesorId { get; set; }
    
        public virtual Alunmos_Materias Alunmos_Materias { get; set; }
        public virtual Profesores Profesores { get; set; }
    }
}
